default_platform(:android)

platform :android do
  desc "Deploy a new version to the Google Play"
  lane :deploy do
    upload_to_play_store(
      track: 'internal',
      aab: '../build/app/outputs/bundle/release/app-release.aab',
      skip_upload_metadata: true,
      package_name: 'com.pcss.clinical_decision_support',
      release_status: 'draft',
      skip_upload_screenshots: true
    )
  end
end
