from reportlab.lib.pagesizes import letter
from reportlab.pdfgen import canvas
from reportlab.lib.utils import ImageReader
import io
import datetime
import textwrap

class ReportGenerator:
    def create_report(self, patient_id, patient_name, dob, email, findings, original_image_bytes, heatmap_image_bytes=None, pinpoint_image_bytes=None, doctor_marked_images_bytes=None, model_info="Standard Model", is_ecg=False, waveform_image_bytes=None):
        from reportlab.lib import colors
        
        buffer = io.BytesIO()
        c = canvas.Canvas(buffer, pagesize=letter)
        width, height = letter
        
        # Color Palette
        primary_color = colors.HexColor("#3F51B5") # Indigo
        secondary_color = colors.HexColor("#E8EAF6") # Light Indigo
        text_color = colors.HexColor("#212121")
        accent_color = colors.HexColor("#FF5252") # Red for disclaimer
        
        def draw_header(c, title):
            c.saveState()
            c.setFillColor(primary_color)
            c.rect(0, height - 80, width, 80, fill=True, stroke=False)
            
            # Embed Logo if exists
            try:
                logo_path = "assets/logo.png"
                c.drawImage(logo_path, 40, height - 70, width=60, height=60, mask='auto', preserveAspectRatio=True)
                title_x = 110
            except:
                title_x = 40
            
            # Title at the bottom-left of the header
            c.setFont("Helvetica-Bold", 18)
            c.setFillColor(colors.white)
            c.drawString(title_x, height - 60, "Pilti Clinical Support System (PCSS)")
            
            # Metadata at the top-right of the header
            c.setFont("Helvetica", 9)
            c.drawRightString(width - 20, height - 15, f"Generated: {datetime.datetime.now().strftime('%Y-%m-%d %H:%M')}")
            c.drawRightString(width - 20, height - 25, f"Patient: {str(patient_name)} (Report ID: {str(patient_id)})")
            c.drawRightString(width - 20, height - 35, f"Patient Date of Birth: {str(dob)}")
            c.drawRightString(width - 20, height - 45, f"Account Email: {str(email)}")
            c.restoreState()

        def draw_footer(c, page_num):
            c.saveState()
            c.setStrokeColor(colors.lightgrey)
            c.line(40, 50, width - 40, 50)
            c.setFont("Helvetica-Oblique", 8)
            c.setFillColor(colors.grey)
            c.drawString(40, 35, "Confidential Medical Documentation - AI Assisted Analysis")
            c.drawRightString(width - 40, 35, f"Page {page_num}")
            c.restoreState()

        # --- PAGE 1: Summary & Thumbnails ---
        
        report_title = "ECG Cardiac Analysis Report" if is_ecg else "Radiology Analysis Report"
        draw_header(c, report_title)
        
        # Disclaimer Box
        c.setStrokeColor(accent_color)
        c.setFillColor(colors.HexColor("#FFEBEE")) # Light Red
        c.roundRect(40, height - 150, width - 80, 50, 5, fill=True, stroke=True)
        
        c.setFont("Helvetica-Bold", 12)
        c.setFillColor(accent_color)
        c.drawString(55, height - 120, "⚠ DISCLAIMER: NOT A MEDICAL DIAGNOSIS")
        c.setFillColor(text_color)
        c.setFont("Helvetica", 10)
        
        disclaimer_text = "This report is generated by an AI system. It must be verified by a qualified physician."
        if is_ecg:
            disclaimer_text = "Cardiac metrics and arrhythmia findings are automated and must be verified by a clinician/cardiologist."
            
        c.drawString(55, height - 135, disclaimer_text)
        
        # Findings Section
        y = height - 190
        c.setFont("Helvetica-Bold", 16)
        c.setFillColor(primary_color)
        c.drawString(40, y, "Findings Summary")
        c.line(40, y-5, width-40, y-5)
        
        y -= 40
        
        # --- Explanations Dictionary ---
        xray_explanations = {
            "Atelectasis": "Partial collapse or incomplete expansion of the lung.\nThis may occur due to blockage of the air passages (bronchus or bronchioles) or by pressure on the outside of the lung.\nCommon causes include mucus plugs, foreign bodies, or tumors.\nIt is often reversible with treatment.",
            "Cardiomegaly": "Enlargement of the heart beyond normal dimensions.\nThis can be a sign of heart failure, high blood pressure, or other heart conditions.\nIt is typically assessed by the cardiothoracic ratio on a PA chest X-ray.\nFurther cardiac evaluation (ECHO) is usually recommended.",
            "Effusion": "Accumulation of fluid in the pleural space around the lungs.\nThis can compress the lung and cause shortness of breath.\nCauses include heart failure, pneumonia, cancer, or kidney disease.\nSmall effusions may resolve, but large ones may require drainage.",
            "Infiltration": "Presence of a substance denser than air, such as pus, blood, or protein, within the lung tissue.\nThis is a non-specific finding often associated with pneumonia or other infections.\nIt appears as ill-defined whiteness on the X-ray.\nClinical correlation with symptoms is essential.",
            "Mass": "A defined growth or lesion within the lung greater than 3cm in diameter.\nThis requires immediate investigation to rule out malignancy (lung cancer).\nHowever, it can also be a benign tumor or abscess.\nCT scan is typically the next step for characterization.",
            "Nodule": "A small, round growth in the lung, less than 3cm in diameter.\nMany nodules are benign (harmless), caused by past infections or scars.\nHowever, some can be early stage lung cancer.\nFollow-up imaging or biopsy may be needed based on size and risk factors.",
            "Pneumonia": "Infection of one or both lungs caused by bacteria, viruses, or fungi.\nThe air sacs may fill with fluid or pus (purulent material).\nSymptoms often include cough, fever, and difficulty breathing.\nAntibiotics or antivirals are the standard treatment.",
            "Pneumothorax": "Presence of air in the pleural space causing lung collapse.\nThis can occur spontaneously or due to trauma/injury.\nSmall cases may resolve on their own with oxygen therapy.\nLarger cases require a chest tube to drain the air.",
            "Consolidation": "Solidification of lung tissue due to filling of alveoli with fluid or cells.\nThis is a classic sign of pneumonia (bacterial).\nIt appears as a dense white area on the X-ray.\nBreath sounds may be altered over the affected area.",
            "Edema": "Fluid accumulation in the lung tissue (pulmonary edema).\nMost commonly caused by congestive heart failure (excess pressure in blood vessels).\nIt creates a 'bat-wing' or hazy appearance on X-ray.\nDiuretics are often used to remove excess fluid.",
            "Emphysema": "A type of COPD involving damage to the air sacs (alveoli).\nThe lungs become hyperinflated (too much air).\nThe diaphragm appears flattened on X-ray.\nSmoking is the primary cause.",
            "Fibrosis": "Scarring of the lung tissue.\nThis stiffens the lungs and makes breathing difficult.\nCauses include chronic inflammation, autoimmune diseases, or environmental exposure.\nThe scarring is permanent but progression can sometimes be slowed.",
            "Pleural_Thickening": "Thickening of the lining of the lungs (pleura).\nOften a result of past inflammation, infection, or asbestos exposure.\nIt can restrict lung expansion.\nIt is usually permanent.",
            "Hernia": "Protrusion of abdominal contents into the chest cavity.\nMost commonly a hiatal hernia (stomach moving up).\nCan cause heartburn or chest pain.\nOften an incidental finding on CXR.",
            "Lung Opacity": "A broad term for any area of the lung that appears whiter than expected.\nThis can represent pneumonia, fluid, scarring, or a tumor.\nIt indicates that the lung tissue is denser than normal air.\nRequires clinical correlation with patient symptoms.",
            "Enlarged Cardiomediastinum": "An abnormally wide appearance of the middle chest area.\nCan be caused by a large heart, aortic issues, or lymph node enlargement.\nFurther imaging like CT or ECHO is often required for clarification.\nCan sometimes be due to techincal factors like patient positioning.",
            "Lung Lesion": "A suspicious area of abnormal tissue in the lung (like a nodule or mass).\nCan be benign (scarring) or malignant (early-stage cancer).\nRequires close monitoring or follow-up imaging (CT scan).\nRadiological characterization is essential for management.",
            "Fracture": "A break or crack in the bones visible on the X-ray (usually ribs or clavicle).\nCan be a results of trauma, coughing, or bone weakness (osteoporosis).\nOld healing fractures are also common incidental findings.\nMay require pain management or further orthopedic review."
        }

        ecg_explanations = {
            "Normal Sinus Rhythm": "The heart's natural pacemaker (sinus node) is firing at a normal rate and rhythm.\nThis indicates a healthy electrical conduction pattern through the atria and ventricles.",
            "Sinus Bradycardia": "A heart rate slower than 60 beats per minute.\nThis can be normal in well-trained athletes or during sleep.\nHowever, if accompanied by dizziness or fatigue, it may require clinical review.",
            "Sinus Tachycardia": "A heart rate faster than 100 beats per minute.\nCommonly a normal response to stress, physical exertion, or dehydration.\nPersistent resting tachycardia should be evaluated by a physician.",
            "Reduced HR Variability": "A reduction in the variation between consecutive heartbeats (SDNN < 20ms).\nLower HRV may correlate with increased physiological stress, autonomic fatigue, or chronic conditions.\nRequires correlation with clinical history.",
            "Insufficient signal quality": "The AI vision system was unable to extract a reliable 1D electrical signal from the paper scan.\nThis is often due to low image contrast, excessive paper folds, or obstructed grid lines.",
            "Arrhythmia Detected": "The model has identified irregularities in the heart rhythm timing or waveform structure.\nThis necessitates a manual review of the ECG tracing by a qualified cardiologist."
        }
        
        explanations = ecg_explanations if is_ecg else xray_explanations
        
        predictions = findings.get('predictions', {})
        if not isinstance(predictions, dict):
             predictions = {k:v for k,v in findings.items() if isinstance(v, (int, float))}
            
        doctor_notes = findings.get('doctor_notes', '')
        sorted_findings = sorted(predictions.items(), key=lambda x: x[1], reverse=True)
        
        # Narrative Analysis Summary
        c.setFillColor(secondary_color)
        c.roundRect(40, y - 120, width - 80, 120, 5, fill=True, stroke=False)
        
        c.setFillColor(text_color)
        c.setFont("Helvetica", 11)
        
        if is_ecg:
            # ECG Narrative
            hr = findings.get('Heart Rate (BPM)', 'N/A')
            hrv = findings.get('HRV (SDNN)', 'N/A')
            top_finding = findings.get('findings', ['Normal Sinus Rhythm'])[0] if isinstance(findings.get('findings'), list) else "Normal Sinus Rhythm"
            
            narrative = f"The PCSS HeartEye analysis has processed the paper ECG scan. "
            narrative += f"The primary rhythm interpretation is '{top_finding}'. "
            narrative += f"The recorded average Heart Rate is {hr} BPM, with an HRV (SDNN) of {hrv} ms. "
            narrative += "\n\nClinical verification of the digitized waveform is essential. The reconstruction displays the extracted 1D signal for visual review."
        else:
            # Radiology Narrative
            top_finding = findings.get('top_finding', "No Findings")
            top_prob = predictions.get(top_finding, 0.0)
            significant_others = [name for name, prob in predictions.items() if prob > 0.2 and name != top_finding]
            
            narrative = f"The PCSS 'Radiologist Eye' model has performed a comprehensive analysis of the chest X-ray. "
            if top_finding == "No Findings" or top_prob < 0.15:
                narrative += "The analysis did not identify any significant radiological abnormalities above clinical thresholds. The lung fields appear clear, and cardiomediastinal borders are within normal limits."
            else:
                narrative += f"The primary observation identified is '{top_finding}' with a confidence level of {top_prob*100:.1f}%. "
                if significant_others:
                    narrative += f"Secondary observations include {', '.join(significant_others)}. "
                narrative += "\n\nClinical correlation is required to assess the significance of these findings. The provided heatmap (Visual Evidence) indicates the specific regions of interest where the model's focus was most concentrated."

        text_object = c.beginText(55, y - 25)
        text_object.setFont("Helvetica", 10)
        text_object.setTextOrigin(55, y - 25)
        text_object.setLeading(14)
        
        # Simple wrapping
        wrapped_lines = []
        for line in narrative.split('\n'):
            wrapped_lines.extend(textwrap.wrap(line, width=105))
            
        for line in wrapped_lines:
            text_object.textLine(line)
        c.drawText(text_object)

        # --- Clinical Consensus Agent Verdict (Page 1 Focal Point) ---
        if not is_ecg:
            y -= 140 # Move down below narrative box
            consensus = findings.get('consensus', {})
            if consensus:
                status = consensus.get('status', 'UNCERTAIN')
                reason = consensus.get('reason', 'Consensus verification in progress.')
                
                # Consensus Box
                box_color = colors.green if status == "APPROVED" else (colors.red if status == "CONFLICT" else colors.grey)
                c.setFillColor(box_color)
                c.roundRect(40, y - 60, width - 80, 60, 5, fill=True, stroke=False)
                
                c.setFillColor(colors.white)
                c.setFont("Helvetica-Bold", 12)
                c.drawString(55, y - 20, f"CONSENSUS VERDICT: {status}")
                
                c.setFont("Helvetica-Oblique", 9)
                c.drawString(55, y - 35, f"Agent: {consensus.get('agent_name', 'PCSS Clinical Auditor')}")
                
                c.setFont("Helvetica", 10)
                wrapped_reason = textwrap.wrap(reason, width=85)
                for i, r_line in enumerate(wrapped_reason[:2]):
                    c.drawString(55, y - 50 - (i*12), r_line)
        
        y -= 140
            
        # Doctor's Notes Section (Always Show)
        c.setFillColor(secondary_color)
        c.roundRect(40, 230, width - 80, 60, 5, fill=True, stroke=False)
        
        c.setFillColor(text_color)
        c.setFont("Helvetica-Bold", 12)
        c.drawString(50, 275, "Doctor's Notes / Recommendations:")
        
        c.setFont("Helvetica-Oblique", 10)
        final_notes = doctor_notes if doctor_notes and doctor_notes.strip() else "Doctor did not provide any additional specific details or recommendations."
        c.drawString(50, 255, str(final_notes))
        
        # Visual Evidence (Thumbnails) - Group Centered with proper spacing
        c.setFont("Helvetica-Bold", 14)
        c.setFillColor(primary_color)
        c.drawString(40, 220, "Visual Evidence")
        c.line(40, 215, width-40, 215)

        thumb_y = 80
        thumb_size = 125
        gap = 40
        
        # Calculate centering for the group of images
        num_images = 0
        if original_image_bytes: num_images += 1
        if heatmap_image_bytes: num_images += 1
        if waveform_image_bytes: num_images += 1
        
        total_width = (num_images * thumb_size) + ((num_images - 1) * gap if num_images > 1 else 0)
        start_x = (width - total_width) / 2

        current_x = start_x
        if original_image_bytes:
            try:
                img = ImageReader(io.BytesIO(original_image_bytes))
                c.drawImage(img, current_x, thumb_y, width=thumb_size, height=thumb_size, preserveAspectRatio=True)
                c.setFont("Helvetica-Bold", 10)
                label = "Paper Scan" if is_ecg else "Original Scan"
                c.drawCentredString(current_x + (thumb_size/2), thumb_y - 15, label)
                current_x += (thumb_size + gap)
            except Exception as e:
                print(f"Error embedding original image: {e}")

        if heatmap_image_bytes and not is_ecg:
            try:
                img_heat = ImageReader(io.BytesIO(heatmap_image_bytes))
                c.drawImage(img_heat, current_x, thumb_y, width=thumb_size, height=thumb_size, preserveAspectRatio=True)
                c.setFont("Helvetica-Bold", 10)
                c.drawCentredString(current_x + (thumb_size/2), thumb_y - 15, "AI Analysis Overlay")
                current_x += (thumb_size + gap)
            except Exception as e:
                print(f"Error embedding heatmap image: {e}")

        if waveform_image_bytes:
            try:
                img_wave = ImageReader(io.BytesIO(waveform_image_bytes))
                c.drawImage(img_wave, current_x, thumb_y, width=thumb_size, height=thumb_size, preserveAspectRatio=True)
                c.setFont("Helvetica-Bold", 10)
                c.drawCentredString(current_x + (thumb_size/2), thumb_y - 15, "Digitized Signal")
            except Exception as e:
                print(f"Error embedding waveform image: {e}")

        current_page = 1
        draw_footer(c, current_page)
        c.showPage()
        
        # --- PAGE 2: Full Original X-Ray ---
        current_page += 1
        draw_header(c, "Original X-Ray Scan")
        if original_image_bytes:
            try:
                img = ImageReader(io.BytesIO(original_image_bytes))
                c.drawImage(img, 40, 100, width=width-80, height=height-230, preserveAspectRatio=True)
                # Add caption
                c.setFont("Helvetica-Bold", 11)
                c.setFillColor(colors.HexColor("#2E3B4E"))
                caption_text = "Figure 1: Original X-Ray Scan - Unprocessed radiographic image"
                text_width = c.stringWidth(caption_text, "Helvetica-Bold", 11)
                c.drawString((width - text_width) / 2, 85, caption_text)
            except:
                pass
        draw_footer(c, current_page)
        c.showPage()

        # --- PAGE 3: Full Heatmap/Waveform X-Ray ---
        current_page += 1
        if is_ecg and waveform_image_bytes:
             draw_header(c, "Digitized ECG Signal")
             try:
                img_wave = ImageReader(io.BytesIO(waveform_image_bytes))
                c.drawImage(img_wave, 40, 100, width=width-80, height=height-230, preserveAspectRatio=True)
                # Add caption
                c.setFont("Helvetica-Bold", 11)
                c.setFillColor(colors.HexColor("#2E3B4E"))
                caption_text = "Figure 2: Digitized ECG Signal - Processed clinical tracing"
                text_width = c.stringWidth(caption_text, "Helvetica-Bold", 11)
                c.drawString((width - text_width) / 2, 85, caption_text)
             except:
                pass
        elif not is_ecg and heatmap_image_bytes:
            draw_header(c, "AI Analysis Overlay")
            try:
                img_heat = ImageReader(io.BytesIO(heatmap_image_bytes))
                c.drawImage(img_heat, 40, 100, width=width-80, height=height-230, preserveAspectRatio=True)
                # Add caption
                c.setFont("Helvetica-Bold", 11)
                c.setFillColor(colors.HexColor("#2E3B4E"))
                caption_text = "Figure 2: AI Analysis Heatmap - Regions of interest highlighted by the AI model"
                text_width = c.stringWidth(caption_text, "Helvetica-Bold", 11)
                c.drawString((width - text_width) / 2, 85, caption_text)
            except:
                pass
        else:
             draw_header(c, "Analysis Visualization")
             c.setFont("Helvetica", 12)
             c.drawCentredString(width/2, height/2, "No secondary visualization available.")

        draw_footer(c, current_page)
        c.showPage()
        
        # --- PAGE 4: Focal Point (Pinpoint Crop) ---
        if not is_ecg and pinpoint_image_bytes:
            current_page += 1
            draw_header(c, "Pathological Focal Point")
            try:
                img_pin = ImageReader(io.BytesIO(pinpoint_image_bytes))
                c.drawImage(img_pin, (width-300)/2, 250, width=300, height=300, preserveAspectRatio=True)
                
                # Add highlighting caption
                c.setFont("Helvetica-Bold", 11)
                c.setFillColor(colors.HexColor("#2E3B4E"))
                caption_text = "Figure 3: Focal Point Analysis - AI identifies the most suspicious region."
                text_width = c.stringWidth(caption_text, "Helvetica-Bold", 11)
                c.drawString((width - text_width) / 2, 220, caption_text)
                
                # Description box
                c.setFillColor(secondary_color)
                c.roundRect(40, 100, width - 80, 80, 5, fill=True, stroke=False)
                c.setFillColor(text_color)
                c.setFont("Helvetica-Bold", 10)
                c.drawString(55, 165, "Technical Note:")
                c.setFont("Helvetica", 9)
                desc = "This image is an automated pinpoint crop showing the area with the highest model attention. "
                desc += "Clinicians should carefully review this region for early signs of the identified pathology."
                text_object = c.beginText(55, 150)
                for line in textwrap.wrap(desc, width=95):
                    text_object.textLine(line)
                c.drawText(text_object)
                
            except Exception as e:
                print(f"Error embedding pinpoint image: {e}")
            
            draw_footer(c, current_page)
            c.showPage()

        # --- PAGE 4+: Doctor's Clinical Annotations ---
        if doctor_marked_images_bytes:
            for i, img_bytes in enumerate(doctor_marked_images_bytes):
                current_page += 1
                draw_header(c, f"Doctor's Clinical Annotation {i+1}")
                try:
                    img_marked = ImageReader(io.BytesIO(img_bytes))
                    c.drawImage(img_marked, 40, 100, width=width-80, height=height-230, preserveAspectRatio=True)
                    # Add caption
                    c.setFont("Helvetica-Bold", 11)
                    c.setFillColor(colors.HexColor("#2E3B4E"))
                    caption_text = f"Figure {3+i}: Clinical Annotation {i+1} - Annotated by the reviewing physician"
                    text_width = c.stringWidth(caption_text, "Helvetica-Bold", 11)
                    c.drawString((width - text_width) / 2, 85, caption_text)
                except Exception as e:
                    print(f"Error embedding marked image {i}: {e}")
                draw_footer(c, current_page)
                c.showPage()
            
        # --- TECHNICAL APPENDIX ---
        current_page += 1
        draw_header(c, "Technical Appendix")
        
        # Patient Info
        c.setFont("Helvetica-Bold", 12)
        c.drawString(50, height - 140, "Patient Name:")
        c.drawString(300, height - 140, "Report ID:")
        c.drawString(50, height - 160, "Patient Date of Birth:")
        c.drawString(300, height - 160, "Account Email:")
        
        c.setFont("Helvetica", 12)
        c.drawString(150, height - 140, str(patient_name))
        c.drawString(400, height - 140, str(patient_id))
        c.drawString(200, height - 160, str(dob))
        c.drawString(400, height - 160, str(email))
        
        y = height - 120 # This y will be overwritten by the next y calculation
        y = height - 200 # Adjust y to start below patient info
        c.setFont("Helvetica-Bold", 14)
        c.setFillColor(primary_color)
        c.drawString(40, y, "Full Confidence Scores")
        c.line(40, y-5, width-40, y-5)
        y -= 30
        
        c.setFont("Helvetica", 10)
        c.setFillColor(text_color)
        
        if is_ecg:
            # Table Header
            c.setFillColor(colors.lightgrey)
            c.rect(40, y, width-80, 20, fill=True, stroke=False)
            c.setFillColor(colors.black)
            c.setFont("Helvetica-Bold", 10)
            c.drawString(50, y+5, "METRIC")
            c.drawString(250, y+5, "VALUE")
            c.drawString(450, y+5, "SIGNIFICANCE")
            y -= 25
            
            for i, (metric, val) in enumerate(findings.items()):
                if metric in ['findings', 'doctor_notes', 'predictions', 'top_finding']: continue
                # Row Background
                if i % 2 == 0:
                    c.setFillColor(colors.whitesmoke)
                    c.rect(40, y, width-80, 20, fill=True, stroke=False)
                
                c.setFillColor(colors.black)
                c.setFont("Helvetica", 10)
                c.drawString(50, y+5, metric)
                c.drawString(250, y+5, str(val))
                
                significance = "Normal Range"
                if "BPM" in metric:
                    try:
                        fval = float(val)
                        if fval < 60: significance = "BRADYCARDIA"
                        elif fval > 100: significance = "TACHYCARDIA"
                    except: pass
                
                c.setFont("Helvetica-Bold", 10)
                c.drawString(450, y+5, significance)
                y -= 20
        else:
            # Table Header
            c.setFillColor(colors.lightgrey)
            c.rect(40, y, width-80, 20, fill=True, stroke=False)
            c.setFillColor(colors.black)
            c.setFont("Helvetica-Bold", 10)
            c.drawString(50, y+5, "CONDITION")
            c.drawString(250, y+5, "PROBABILITY")
            c.drawString(450, y+5, "RISK LEVEL")
            y -= 25
            
            for i, (condition, prob) in enumerate(sorted_findings):
                # Row Background
                if i % 2 == 0:
                    c.setFillColor(colors.whitesmoke)
                    c.rect(40, y, width-80, 20, fill=True, stroke=False)
                
                c.setFillColor(colors.black)
                c.setFont("Helvetica", 10)
                c.drawString(50, y+5, condition)
                c.drawString(250, y+5, f"{prob:.4f}")
                
                risk_label = "LOW"
                if prob > 0.7: 
                    risk_label = "HIGH"
                    c.setFillColor(colors.red)
                elif prob > 0.3: 
                    risk_label = "MODERATE"
                    c.setFillColor(colors.orange)
                else:
                    c.setFillColor(colors.green)
                
                c.setFont("Helvetica-Bold", 10)
                c.drawString(450, y+5, risk_label)
                y -= 20
            
            # Check if we need a new page for Appendix table if it's too long
            if y < 100:
                draw_footer(c, current_page)
                c.showPage()
                current_page += 1
                draw_header(c, "Technical Appendix (Continued)")
                y = height - 120
                
        y -= 30
        c.setFillColor(primary_color)
        c.setFont("Helvetica-Bold", 14)
        c.drawString(40, y, "Model Specifications")
        c.line(40, y-5, width-40, y-5)
        y -= 25

        c.setFillColor(text_color)
        c.setFont("Helvetica", 10)
        
        if is_ecg:
            specs = [
                ("Architecture", "HuBERT-ECG (Next-Gen Cardio-Transformer)"),
                ("Sampling Rate", "250 Hz (Digitized) / 100 Hz (Inference)"),
                ("Normalization", "Z-Score (Mean/Std Scaling)"),
                ("Analysis Engine", "Multi-Agent (Transformer + Clinical Auditor)"),
                ("Plotting", "High-Fidelity 1D Waveform Reconstruction")
            ]
        else:
            specs = [
                ("Architecture", model_info),
                ("Input Resolution", "224x224 Grayscale"),
                ("Normalization", "XRV Standard (-1024 to 1024 scale)"),
                ("Heatmap Method", "RAD-DINO Attention Rollout (Next-Gen ViT)"),
                ("Colormap", "JET (Blue=Low, Red=High)")
            ]
        
        for label, value in specs:
            c.setFont("Helvetica-Bold", 10)
            c.drawString(50, y, str(label) + ":")
            c.setFont("Helvetica", 10)
            c.drawString(200, y, str(value) if value is not None else "N/A")
            y -= 15
        
        draw_footer(c, current_page)
        c.showPage()
        
        # --- Pathological Appendix ---
        pathology_list = sorted(explanations.keys())
        items_per_page = 6
        
        for i in range(0, len(pathology_list), items_per_page):
            current_page += 1
            draw_header(c, f"Technical Appendix - Clinical Categories (Part {i//items_per_page + 1})")
            
            y = height - 120
            c.setFont("Helvetica-Bold", 14)
            c.setFillColor(primary_color)
            c.drawString(40, y, "Pathology Deep-Dive (Technical Perspective)")
            c.line(40, y-5, width-40, y-5)
            y -= 40
            
            page_items = pathology_list[i:i + items_per_page]
            for condition in page_items:
                # Section Box
                box_height = 90
                c.setFillColor(secondary_color)
                c.roundRect(40, y - box_height, width - 80, box_height, 5, fill=True, stroke=False)
                
                c.setFillColor(text_color)
                c.setFont("Helvetica-Bold", 12)
                c.drawString(55, y - 20, condition)
                
                # Probability if exists
                prob = predictions.get(condition, 0)
                pill_color = colors.green if prob < 0.3 else (colors.orange if prob < 0.7 else colors.red)
                c.setFillColor(pill_color)
                c.roundRect(width - 170, y - 25, 120, 18, 9, fill=True, stroke=False)
                c.setFillColor(colors.white)
                c.setFont("Helvetica-Bold", 9)
                c.drawCentredString(width - 110, y - 19, f"{prob*100:.2f}% Prob")
                
                # Technical Explanation
                c.setFillColor(text_color)
                c.setFont("Helvetica", 9)
                explanation = explanations.get(condition, "No description.")
                text_object = c.beginText(55, y - 40)
                text_object.setLeading(11)
                for line in explanation.split('\n'):
                    text_object.textLine(line)
                c.drawText(text_object)
                
                y -= (box_height + 15)
                
            draw_footer(c, current_page)
            c.showPage()
            
        c.save()
        buffer.seek(0)
        return buffer.getvalue()
