# Flutter analyzer configuration for CI/CD
include: package:flutter_lints/flutter.yaml

analyzer:
  exclude:
    - "**/*.g.dart"
    - "**/*.freezed.dart"
  errors:
    # Treat warnings as infos to allow CI to pass
    unused_import: info
    unused_local_variable: info
    unused_field: info
    deprecated_member_use: info

linter:
  rules:
    # Disable rules that are informational but not critical for production
    avoid_print: false  # We use print for debugging, can be replaced with logging later
    use_build_context_synchronously: false  # We use mounted checks appropriately
    avoid_web_libraries_in_flutter: false  # Needed for web-specific implementations
    prefer_interpolation_to_compose_strings: false
    use_rethrow_when_possible: false
    unnecessary_to_list_in_spreads: false
    
    # Keep important rules enabled
    prefer_const_constructors: true
    prefer_const_literals_to_create_immutables: true
    avoid_unnecessary_containers: true
    sized_box_for_whitespace: true
